source "https://rubygems.org"

# Essential gems for iOS development
gem "fastlane"
gem "cocoapods", "~> 1.12.0"  # Specific newer version to support RNScreens

# Plugin requirements are handled by the Pluginfile - no need to specify them here
# gem "fastlane-plugin-firebase_app_distribution"

# Add other gems as needed

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path) 