name: Upload iOS App to TestFlight

on:
  push:
    branches:
      - main   
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  build-and-upload:
    runs-on: macos-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/ios/Gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper version numbering

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Using Node 18 for better compatibility with Expo
          cache: 'npm'

      - name: Install JS dependencies
        run: |
          npm ci
          npx expo install --check

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'ios'

      - name: Install Fastlane and CocoaPods
        run: |
          cd ios
          gem install fastlane cocoapods
          pod install

      - name: Configure Apple Credentials
        env:
          APPSTORE_API_KEY_BASE64: ${{ secrets.APPLE_PRIVATE_KEY }}
          APPLE_API_KEY_ID: ${{ vars.APPSTORE_KEY_ID }}
          APPLE_ISSUER_ID: ${{ vars.APPSTORE_ISSUER_ID }}
        run: |
          mkdir -p ~/private_keys
          echo -n "$APPSTORE_API_KEY_BASE64" | base64 --decode > ~/private_keys/AuthKey.p8
          echo "API_KEY_PATH=~/private_keys/AuthKey.p8" >> $GITHUB_ENV
          echo "API_KEY_ID=$APPLE_API_KEY_ID" >> $GITHUB_ENV
          echo "ISSUER_ID=$APPLE_ISSUER_ID" >> $GITHUB_ENV

      - name: Build and Upload to TestFlight
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          cd ios
          bundle exec fastlane beta
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/build/*.ipa
          retention-days: 5
