name: Upload iOS App to TestFlight

on:
  push:
    branches:
      - main   
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  build-and-upload:
    runs-on: macos-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/ios/Gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper version numbering

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Using Node 18 for better compatibility with Expo
          cache: 'npm'

      - name: Install JS dependencies
        run: |
          npm install
          # Update Expo dependencies rather than just checking them
          npx expo install expo-router@~4.0.21
          # Continue even if expo check reports issues
          npx expo install --check || true

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Ruby and bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Updated from 3.0 to 3.2 for Bundler 2.6.9 compatibility
          bundler-cache: false  # Disable automatic bundler cache to handle platform differences
          working-directory: 'ios'

      - name: Install dependencies with Bundler
        run: |
          cd ios
          # Add the current platform to the lockfile
          bundle lock --add-platform arm64-darwin-23
          bundle lock --add-platform arm64-darwin
          bundle lock --add-platform x86_64-darwin
          # Install gems from Gemfile
          bundle install
          
      - name: Patch RNScreens Podspec
        run: |
          # Create backup of original podspec
          cp node_modules/react-native-screens/RNScreens.podspec node_modules/react-native-screens/RNScreens.podspec.bak
          # Remove the problematic project_header_files line
          sed -i '' '/project_header_files/d' node_modules/react-native-screens/RNScreens.podspec
          echo "Patched RNScreens.podspec to remove unsupported property"
          
      - name: Install CocoaPods
        run: |
          cd ios
          bundle exec pod install

      - name: Configure Apple Credentials
        env:
          APPSTORE_API_KEY_BASE64: ${{ secrets.APPLE_PRIVATE_KEY }}
          APPLE_API_KEY_ID: ${{ vars.APPSTORE_KEY_ID }}
          APPLE_ISSUER_ID: ${{ vars.APPSTORE_ISSUER_ID }}
        run: |
          mkdir -p ~/private_keys
          echo -n "$APPSTORE_API_KEY_BASE64" | base64 --decode > ~/private_keys/AuthKey.p8
          echo "API_KEY_PATH=~/private_keys/AuthKey.p8" >> $GITHUB_ENV
          echo "API_KEY_ID=$APPLE_API_KEY_ID" >> $GITHUB_ENV
          echo "ISSUER_ID=$APPLE_ISSUER_ID" >> $GITHUB_ENV

      - name: Build and Upload to TestFlight
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          cd ios
          bundle exec fastlane beta
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/build/*.ipa
          retention-days: 5
